version: '3.6'
services:
  fake-gcs:
    image: fsouza/fake-gcs-server:latest
    container_name: api-campaigns-fake-gcs
    ports:
      - 4443:4443
    volumes:
      - ./test/assets/dummy_gcs:/data
    command: ['-scheme', 'http', '-backend', 'memory']

  unlayer-export:
    restart: always
    image: us.gcr.io/beamery-global/export-api:latest
    container_name: api-campaigns-unlayer-export
    environment:
      API_KEY: test-api-key
    ports:
      - 8080:8080
