version: "3.6"
services:
  mongo:
    image: mongo:4.4
    container_name: api-campaigns-mongodb
    ports:
       - 27017:27017
    volumes:
        - ./util/mongo/local-mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
