name: 'Test'

on: [push]

jobs:
  jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 18

      - uses: actions/checkout@v2
        with:
          repository: BeameryHQ/actions
          path: .github/BeameryHQ/actions
          token: ${{ secrets.HAL_9000B_TOKEN }}

      - name: Workflow Context
        id: beamery
        uses: ./.github/BeameryHQ/actions/js/workflow-context
        with:
          verdaccio-token: ${{ secrets.VERDACCIO_SUPPORT_TOKEN }}
          atlassian-url: ${{ secrets.ATLASSIAN_BASE_URL }}

      - uses: actions/cache@v2
        id: yarn
        with:
          path: '**/node_modules'
          key: ${{ steps.beamery.outputs.cacheKey }}

      - name: Installing Dependencies
        run: yarn install --frozen-lockfile --silent --prefer-offline

      - name: Jest
        run: yarn test

      - name: Jest e2e
        run: yarn test:e2e
